--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekEasyGamemode
build-by-default: true
branches:
- master
- pm4
projects:
  KygekEasyGamemode:
    path: ""
    lint:
      phpstan: false
...
